#Data indexing
#three types of matrix-like data structure: array, Series and DataFrame
#array is the way of storing matrix data in NumPy, 
#Series and DataFrame are more commonly used in Pandas.
#The Pandas module mainly works with the tabular data
#the NumPy module works with the numerical data.


#Data manipulation in array

In [9]:
import numpy as np
np.random.seed(123)#Setting a seed = 123 help us generate the exact same numbers
m1 = np.random.randint(0, 100, size = 10) 
m2 = np.random.randint(10, size=(3, 4)) 
print("The one-dimensional array looks like this:\n", m1)
print("The two-dimensional array looks like this:\n", m2)

The one-dimensional array looks like this:
 [66 92 98 17 83 57 86 97 96 47]
The two-dimensional array looks like this:
 [[9 0 0 9]
 [3 4 0 0]
 [4 1 7 3]]


#Accessing single elements

In [27]:
m1[0]
m1[2]

98

In [28]:
#count from the end
m1[-2]

96

In [29]:
m2[0, -1] # First row, last column

9

In [30]:
m2[2,3]

3

#Accessing subarrays

In [31]:
#x[start:stop:step]
m1[0:8:3]

array([66, 17, 86])

In [32]:
m1[:5] # accessing the first five elements

array([66, 92, 98, 17, 83])

In [33]:
m1[5:] # accessing elements after the sixth element

array([57, 86, 97, 96, 47])

In [35]:
m1[::2] # every other elements, step=2

array([66, 98, 83, 86, 96])

In [36]:
m1[1::2] #access every other element starting from the second

array([92, 17, 57, 97, 47])

In [37]:
m1[::-1] # all elements, reversed

array([47, 96, 97, 86, 57, 83, 17, 98, 92, 66])

#Multi-dimensional slices work in the same way, with multiple slices separated by commas. 

In [38]:
m2[:2, :3] # first two rows, first three columns

array([[9, 0, 0],
       [3, 4, 0]])

In [39]:
m2[:, 0]

array([9, 3, 4])

In [40]:
m2[0, :] 

array([9, 0, 0, 9])

In [41]:
m2[m2 > 1]

array([9, 9, 3, 4, 4, 7, 3])

In [43]:
m2[m2>=1]

array([9, 9, 3, 4, 4, 1, 7, 3])

#np.concatenate: stacking arrays of same dimension together
#np.vstack: similar to np.concatenate, but clearer. Stack arrays together vertically.
#np.hstack: Stack arrays together horizontally.

In [44]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [45]:
np.vstack([grid, grid+1])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [5, 6, 7]])

In [46]:
np.hstack([grid, grid+1])

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 5, 6, 7]])

#Data indexing in Series

In [52]:
import pandas as pd
s1 = pd.Series([0.25, 0.5, 0.75, 1.0],
               index=['a', 'b', 'c', 'd'])
s1

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [55]:
s1['c'] 

0.75

In [82]:
# slicing by explicit index
s1['a':'c'] 

a    0.25
b    0.50
c    0.75
dtype: float64

In [83]:
s1['c':'d']

c    0.75
d    1.00
dtype: float64

In [81]:
s1[0:2] #characters from position 0 (included) to 2 (excluded)

a    0.25
b    0.50
dtype: float64

In [79]:
s1[1:3]

b    0.50
c    0.75
dtype: float64

In [56]:
s1[(s1 > 0.1) & (s1 <= 0.7)]

a    0.25
b    0.50
dtype: float64

In [58]:
s2 = pd.Series(['a', 'b', 'c'], index=[1.3, 3, 5])
s2

1.3    a
3.0    b
5.0    c
dtype: object

In [60]:
s2[3] #cannot be '3', this will be stored as number 

'b'

In [76]:
s2[0:2] # characters from position 0 (included) to 2 (excluded)
#use loc is more clear

1.3    a
dtype: object

In [84]:
s2.loc[1:3] #references the explicit index:

1.3    a
3.0    b
dtype: object

In [85]:
s2.iloc[1:3] # iloc   implicit array-style/Python-style index:

3.0    b
5.0    c
dtype: object

#Data indexing in DataFrame

In [86]:
ICEdata = pd.read_csv("ICE1_Data.csv")

ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  
0                 0.563                   0.519  
1                 0.707                   0.363  
2                 0.716                   0.692  
3                 0.564                   0.477  
4                 0.953                   0.870  
..                  ...                     ...  
417               1.000                   0.936  
418               0.977                   0.867  
419               1.000                   0.994  
420               0.914                   0.961  
421               1.000                   0.972  

[422 rows x 6 columns]

In [87]:
ICEdata['Quality_Review_Score']

0          Developing
1          Developing
2      Well Developed
3          Proficient
4          Proficient
            ...      
417    Well Developed
418        Proficient
419    Well Developed
420    Well Developed
421        Proficient
Name: Quality_Review_Score, Length: 422, dtype: object

#Creating new columns

In [90]:
# create collegeRate=Dividing College enroll rate by graduation rate:     
ICEdata['collegeRate']=ICEdata['college enroll 2010-11']/ICEdata['graduation 2010-11']
ICEdata

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0    01M292           Developing                  C                      C   
1    01M448           Developing                  C                      B   
2    01M450       Well Developed                  A                      B   
3    01M509           Proficient                  C                      C   
4    01M539           Proficient                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
0                 0.563                   0.519     0.921847  
1                 0.707                   0.363     0.513437  
2                 0.716                   0.692     0.966480  
3                 0.564                   0.477     0.845745  
4                 0.953                   0.870     0.912907  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[422 rows x 7 columns]

In [95]:
ICEdata.loc[0] # first row

DBN                           01M292
Quality_Review_Score      Developing
Progress_Rpt_10-11                 C
Student_Progress_10-11             C
graduation 2010-11             0.563
college enroll 2010-11         0.519
collegeRate                 0.921847
Name: 0, dtype: object

In [94]:
ICEdata.loc[:3] # frist row to thrid row 

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
0  01M292           Developing                  C                      C   
1  01M448           Developing                  C                      B   
2  01M450       Well Developed                  A                      B   
3  01M509           Proficient                  C                      C   

   graduation 2010-11  college enroll 2010-11  collegeRate  
0               0.563                   0.519     0.921847  
1               0.707                   0.363     0.513437  
2               0.716                   0.692     0.966480  
3               0.564                   0.477     0.845745

In [92]:
ICEdata.iloc[:3, :2]

DBN Quality_Review_Score
0  01M292           Developing
1  01M448           Developing
2  01M450       Well Developed

In [97]:
ICEdata.loc[:7, :'Progress_Rpt_10-11']

DBN Quality_Review_Score Progress_Rpt_10-11
0  01M292           Developing                  C
1  01M448           Developing                  C
2  01M450       Well Developed                  A
3  01M509           Proficient                  C
4  01M539           Proficient                  A
5  01M696       Well Developed                  B
6  02M047           Proficient                  C
7  02M288           Proficient                  A

In [98]:
ICEdata[ICEdata['graduation 2010-11'] > 0.75]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
4    01M539           Proficient                  A                      A   
5    01M696       Well Developed                  B                      C   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
417  10X696       Well Developed                  A                      A   
418  13K430           Proficient                  B                      B   
419  10X445       Well Developed                  A                      A   
420  14K449       Well Developed                  B                      B   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
4                 0.953                   0.870     0.912907  
5                 0.976                   0.957     0.980533  
7                 0.820                   0.627     0.764634  
9                 0.793                   0.560     0.706179  
10                0.915                   0.796     0.869945  
..                  ...                     ...          ...  
417               1.000                   0.936     0.936000  
418               0.977                   0.867     0.887410  
419               1.000                   0.994     0.994000  
420               0.914                   0.961     1.051422  
421               1.000                   0.972     0.972000  

[135 rows x 7 columns]

#Data masking

In [99]:
m2

array([[9, 0, 0, 9],
       [3, 4, 0, 0],
       [4, 1, 7, 3]])

In [100]:
m2[m2>=3]

array([9, 9, 3, 4, 4, 7, 3])

In [101]:
m2 < 2

array([[False,  True,  True, False],
       [False, False,  True,  True],
       [False,  True, False, False]])

In [ ]:
# & (and), | (or) , ^ (exclusive or), and ~(not).

In [102]:
mask = (m2 > 2) & (m2 <5) 
m2[mask]

array([3, 4, 4, 3])

In [103]:
mask = (m2 > 2) | (m2 <5) 
m2[mask]

array([9, 0, 0, 9, 3, 4, 0, 0, 4, 1, 7, 3])

In [113]:
mask = (m2 > 2) ^ (m2 <5) 
m2[mask]

array([9, 0, 0, 9, 0, 0, 1, 7])

In [111]:
ICEmask = (ICEdata['graduation 2010-11'] > 0.75) & (ICEdata['Progress_Rpt_10-11'] == 'A') 
ICEdata[ICEmask]

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
4    01M539           Proficient                  A                      A   
7    02M288           Proficient                  A                      B   
9    02M296           Proficient                  A                      A   
10   02M298       Well Developed                  A                      A   
14   02M308       Well Developed                  A                      A   
..      ...                  ...                ...                    ...   
415  02M475       Well Developed                  A                      B   
416  05M692       Well Developed                  A                      B   
417  10X696       Well Developed                  A                      A   
419  10X445       Well Developed                  A                      A   
421  28Q687           Proficient                  A                      B   

     graduation 2010-11  college enroll 2010-11  collegeRate  
4                 0.953                   0.870     0.912907  
7                 0.820                   0.627     0.764634  
9                 0.793                   0.560     0.706179  
10                0.915                   0.796     0.869945  
14                0.762                   0.478     0.627297  
..                  ...                     ...          ...  
415               0.985                   0.854     0.867005  
416               0.982                   0.934     0.951120  
417               1.000                   0.936     0.936000  
419               1.000                   0.994     0.994000  
421               1.000                   0.972     0.972000  

[79 rows x 7 columns]

#Combining datasets in pandas 

#we'll define this function which creates a DataFrame 

In [127]:
def make(cols, ind): #Quickly make a DataFrame
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make('ABCD', range(5))

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [131]:
# By default, the concatenation takes place row-wise within the DataFrame.

df1 = make('ABC', [1, 2,3])
df2 = make('AB', [3, 4])
print(df1, "\n\n\n")
print(df2, "\n\n\n")
print(pd.concat([df1, df2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3 



    A   B
3  A3  B3
4  A4  B4 



    A   B    C
1  A1  B1   C1
2  A2  B2   C2
3  A3  B3   C3
3  A3  B3  NaN
4  A4  B4  NaN


In [132]:
df3 = make_df('ABC', [1, 2]) #which have some (but not all!) columns in common
df4 = make_df('BCD', [3, 4])
print(df3, "\n\n\n")
print(df4, "\n\n\n")
print(pd.concat([df3, df4]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 



    B   C   D
3  B3  C3  D3
4  B4  C4  D4 



     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


#no data are filled with NaN values
#the join is a union of the input columns (join='outer') #并集
#but we can change this to an intersection of the columns using join='inner' #交集

In [133]:
pd.concat([df3, df4], join = 'inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [134]:
pd.concat([df3, df4], join = 'outer')

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

#pd.merge()   I don't recommend

In [135]:
df5 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df6 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
dfm = pd.merge(df5, df6)

print(df5, "\n\n\n")
print(df6, "\n\n\n")
print(dfm)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR 



  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014 



  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [137]:
 #many-to-one join:
df7 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

dfm = pd.merge(df5, df7)
print(df7, "\n\n\n")

print(dfm)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 



  employee        group supervisor
0      Bob   Accounting      Carly
1     Jake  Engineering      Guido
2     Lisa  Engineering      Guido
3      Sue           HR      Steve


#on keyword, which takes a column name or a list of column names:

In [136]:
pd.merge(df5, df6, on='employee')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

#wish to merge two datasets with different column names

In [140]:
df8 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
pd.merge(df5, df8, left_on = 'employee', right_on = 'name')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [141]:
pd.merge(df5, df8, left_on = 'employee', right_on = 'name').drop('name', axis=1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

#the left_index and right_index keywords allow you merge on an index instead.

#Aggregation, grouping, and pivot tables

In [142]:
ICEdata.describe(include = 'all')

DBN Quality_Review_Score Progress_Rpt_10-11 Student_Progress_10-11  \
count      422                  368                310                    310   
unique     422                    6                  5                      5   
top     15K463           Proficient                  A                      C   
freq         1                  186                109                     93   
mean       NaN                  NaN                NaN                    NaN   
std        NaN                  NaN                NaN                    NaN   
min        NaN                  NaN                NaN                    NaN   
25%        NaN                  NaN                NaN                    NaN   
50%        NaN                  NaN                NaN                    NaN   
75%        NaN                  NaN                NaN                    NaN   
max        NaN                  NaN                NaN                    NaN   

        graduation 2010-11  college enroll 2010-11  collegeRate  
count           310.000000              291.000000   291.000000  
unique                 NaN                     NaN          NaN  
top                    NaN                     NaN          NaN  
freq                   NaN                     NaN          NaN  
mean              0.737977                0.531196     0.707836  
std               0.143356                0.193129     0.168986  
min               0.412000                0.141000     0.262570  
25%               0.625250                0.391000     0.589317  
50%               0.726000                0.489000     0.707569  
75%               0.850750                0.656000     0.838918  
max               1.000000                1.000000     1.101227

#Simple methods such as sum(), mean(), median(), min(), and max()

In [143]:
ICEdata.mean()

graduation 2010-11        0.737977
college enroll 2010-11    0.531196
collegeRate               0.707836
dtype: float64

In [144]:
ICEdata['graduation 2010-11'].max()

1.0

In [145]:
ICEdata['college enroll 2010-11'].min()

0.141

#Other Pandas aggregation methods:

#count(): Total number of items
#first(), last(): First and last item
#mean(), median(): Mean and median
#min(), max(): Minimum and maximum
#std(), var(): Standard deviation and variance
#mad(): Mean absolute deviation
#prod(): Product of all items
#sum(): Sum of all items These are all methods of DataFrame and Series objects.

In [147]:
ICEdata['college enroll 2010-11'].prod()

3.8019163565051434e-89

#groupby generally follows three steps: split, apply, and combine:

#The split step involves breaking up and grouping a DataFrame depending on the value of the specified key.
#The apply step involves computing some function, usually an aggregate, transformation, or filtering, within the individual groups.
#The combine step merges the results of these operations into an output array.

In [148]:
ICEdata.groupby('Quality_Review_Score').mean()

graduation 2010-11  \
Quality_Review_Score                                                     
Developing                                                    0.633019   
Outstanding (only an option in 2007-8)                        0.864333   
Proficient                                                    0.729554   
Underdeveloped                                                0.549667   
Underdeveloped with Proficient Features (only a...                 NaN   
Well Developed                                                0.823367   

                                                    college enroll 2010-11  \
Quality_Review_Score                                                         
Developing                                                        0.402830   
Outstanding (only an option in 2007-8)                            0.747667   
Proficient                                                        0.521208   
Underdeveloped                                                    0.350167   
Underdeveloped with Proficient Features (only a...                     NaN   
Well Developed                                                    0.625871   

                                                    collegeRate  
Quality_Review_Score                                             
Developing                                             0.641309  
Outstanding (only an option in 2007-8)                 0.864183  
Proficient                                             0.703604  
Underdeveloped                                         0.631451  
Underdeveloped with Proficient Features (only a...          NaN  
Well Developed                                         0.752696

In [149]:
# We can also just simply index one column
ICEdata.groupby('Quality_Review_Score')['graduation 2010-11'].describe()

count      mean       std  \
Quality_Review_Score                                                            
Developing                                           53.0  0.633019  0.107199   
Outstanding (only an option in 2007-8)                3.0  0.864333  0.102051   
Proficient                                          157.0  0.729554  0.135946   
Underdeveloped                                        6.0  0.549667  0.061805   
Underdeveloped with Proficient Features (only a...    0.0       NaN       NaN   
Well Developed                                       90.0  0.823367  0.121570   

                                                      min      25%    50%  \
Quality_Review_Score                                                        
Developing                                          0.457  0.56300  0.615   
Outstanding (only an option in 2007-8)              0.800  0.80550  0.811   
Proficient                                          0.412  0.63000  0.722   
Underdeveloped                                      0.457  0.51525  0.554   
Underdeveloped with Proficient Features (only a...    NaN      NaN    NaN   
Well Developed                                      0.545  0.72775  0.833   

                                                        75%    max  
Quality_Review_Score                                                
Developing                                          0.69800  0.947  
Outstanding (only an option in 2007-8)              0.89650  0.982  
Proficient                                          0.81100  1.000  
Underdeveloped                                      0.59350  0.624  
Underdeveloped with Proficient Features (only a...      NaN    NaN  
Well Developed                                      0.91875  1.000

#multiple columns to group

In [150]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11']).count().unstack()
## Here unstack() is just to make the data more readable.

DBN                         \
Progress_Rpt_10-11                         A     B     C     D    F   
Quality_Review_Score                                                  
Developing                               4.0  11.0  19.0  16.0  3.0   
Outstanding (only an option in 2007-8)   3.0   NaN   NaN   NaN  NaN   
Proficient                              48.0  65.0  39.0   5.0  NaN   
Underdeveloped                           NaN   NaN   3.0   1.0  2.0   
Well Developed                          53.0  26.0  11.0   NaN  NaN   

                                       Student_Progress_10-11              \
Progress_Rpt_10-11                                          A     B     C   
Quality_Review_Score                                                        
Developing                                                4.0  11.0  19.0   
Outstanding (only an option in 2007-8)                    3.0   NaN   NaN   
Proficient                                               48.0  65.0  39.0   
Underdeveloped                                            NaN   NaN   3.0   
Well Developed                                           53.0  26.0  11.0   

                                                   ... college enroll 2010-11  \
Progress_Rpt_10-11                         D    F  ...                      A   
Quality_Review_Score                               ...                          
Developing                              16.0  3.0  ...                    3.0   
Outstanding (only an option in 2007-8)   NaN  NaN  ...                    3.0   
Proficient                               5.0  NaN  ...                   45.0   
Underdeveloped                           1.0  2.0  ...                    NaN   
Well Developed                           NaN  NaN  ...                   48.0   

                                                              collegeRate  \
Progress_Rpt_10-11                         B     C     D    F           A   
Quality_Review_Score                                                        
Developing                              11.0  16.0  15.0  2.0         3.0   
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN         3.0   
Proficient                              63.0  37.0   4.0  NaN        45.0   
Underdeveloped                           NaN   3.0   1.0  2.0         NaN   
Well Developed                          26.0  11.0   NaN  NaN        48.0   

                                                               
Progress_Rpt_10-11                         B     C     D    F  
Quality_Review_Score                                           
Developing                              11.0  16.0  15.0  2.0  
Outstanding (only an option in 2007-8)   NaN   NaN   NaN  NaN  
Proficient                              63.0  37.0   4.0  NaN  
Underdeveloped                           NaN   3.0   1.0  2.0  
Well Developed                          26.0  11.0   NaN  NaN  

[5 rows x 25 columns]

#aggregate()

In [151]:
ICEdata.groupby('Quality_Review_Score').aggregate(['median', 'min', 'max'])

graduation 2010-11         \
                                                               median    min   
Quality_Review_Score                                                           
Developing                                                      0.615  0.457   
Outstanding (only an option in 2007-8)                          0.811  0.800   
Proficient                                                      0.722  0.412   
Underdeveloped                                                  0.554  0.457   
Underdeveloped with Proficient Features (only a...                NaN    NaN   
Well Developed                                                  0.833  0.545   

                                                           \
                                                      max   
Quality_Review_Score                                        
Developing                                          0.947   
Outstanding (only an option in 2007-8)              0.982   
Proficient                                          1.000   
Underdeveloped                                      0.624   
Underdeveloped with Proficient Features (only a...    NaN   
Well Developed                                      1.000   

                                                   college enroll 2010-11  \
                                                                   median   
Quality_Review_Score                                                        
Developing                                                         0.4030   
Outstanding (only an option in 2007-8)                             0.6920   
Proficient                                                         0.4900   
Underdeveloped                                                     0.3715   
Underdeveloped with Proficient Features (only a...                    NaN   
Well Developed                                                     0.5920   

                                                                 collegeRate  \
                                                      min    max      median   
Quality_Review_Score                                                           
Developing                                          0.165  0.658    0.647416   
Outstanding (only an option in 2007-8)              0.690  0.861    0.862500   
Proficient                                          0.183  0.990    0.699735   
Underdeveloped                                      0.141  0.465    0.712859   
Underdeveloped with Proficient Features (only a...    NaN    NaN         NaN   
Well Developed                                      0.268  1.000    0.765269   

                                                                        
                                                         min       max  
Quality_Review_Score                                                    
Developing                                          0.271829  1.048622  
Outstanding (only an option in 2007-8)              0.853268  0.876782  
Proficient                                          0.296503  1.101227  
Underdeveloped                                      0.262570  0.756567  
Underdeveloped with Proficient Features (only a...       NaN       NaN  
Well Developed                                      0.388970  1.051422

#request the median data of graduation 2010-11 for Quality_Review_Score, Progress_Rpt_10-11:

In [153]:
ICEdata.groupby(['Quality_Review_Score', 'Progress_Rpt_10-11'])['graduation 2010-11'].aggregate('median').unstack()

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN

In [154]:
#use this one is easier 
ICEdata.pivot_table('graduation 2010-11', index='Quality_Review_Score', columns='Progress_Rpt_10-11')

Progress_Rpt_10-11                             A         B         C  \
Quality_Review_Score                                                   
Developing                              0.716500  0.654545  0.639474   
Outstanding (only an option in 2007-8)  0.864333       NaN       NaN   
Proficient                              0.817083  0.722077  0.660333   
Underdeveloped                               NaN       NaN  0.556333   
Well Developed                          0.862472  0.791000  0.711455   

Progress_Rpt_10-11                             D         F  
Quality_Review_Score                                        
Developing                              0.613812  0.504333  
Outstanding (only an option in 2007-8)       NaN       NaN  
Proficient                              0.526400       NaN  
Underdeveloped                          0.457000  0.586000  
Well Developed                               NaN       NaN

#pivot_table uses aggfunc keyword to know median mean 

In [155]:
ICEdata.pivot_table('graduation 2010-11',
                    index='Quality_Review_Score',
                    columns='Progress_Rpt_10-11',
                   aggfunc = 'median')

Progress_Rpt_10-11                          A       B      C      D      F
Quality_Review_Score                                                      
Developing                              0.702  0.6290  0.587  0.615  0.506
Outstanding (only an option in 2007-8)  0.811     NaN    NaN    NaN    NaN
Proficient                              0.806  0.7150  0.662  0.531    NaN
Underdeveloped                            NaN     NaN  0.537  0.457  0.586
Well Developed                          0.879  0.8145  0.676    NaN    NaN